name: Lint and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [18]

    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - run: yarn install
      - run: yarn build
      - run: yarn lint && yarn test
